#!/bin/bash
# Rush 1.0 Critical Features - Bead Creation Script
# Generated by ralph-tui-create-beads skill

set -e

echo "Creating Rush 1.0 Critical Features epic and beads..."

# Quality Gates for Rush (Rust project):
# - cargo test (all tests pass)
# - cargo build --release (builds successfully)
# - cargo clippy -- -D warnings (no clippy warnings)
# - Manual testing where applicable

# Create epic
echo "Creating epic..."
EPIC_ID=$(bd create --type=epic \
  --title="Rush 1.0 Critical Features" \
  --description="Complete the essential missing features to make Rush production-ready for 1.0 release.

## Success Criteria
- All 8 stories completed with tests
- 1.0 release candidate builds successfully
- All existing 109 tests still pass
- Can replace bash/zsh for daily development work
- Installation takes < 5 minutes on any platform
- Documentation updated for all new features" \
  --labels="rush,1.0,epic" \
  --silent)

echo "Epic created: $EPIC_ID"

# Story 3: Robust Pipeline Implementation (Foundation - no dependencies)
echo "Creating Story 3: Robust Pipeline Implementation..."
STORY_3=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-003: Robust Pipeline Implementation" \
  --description="As a power user, I want complex multi-stage pipelines to work reliably so that I can compose commands like any Unix shell.

## Acceptance Criteria
- [ ] Multi-stage pipes work: \`cat file | grep pattern | sort | uniq -c\`
- [ ] Proper error propagation through pipeline
- [ ] Pipeline exit code is last command's exit code
- [ ] SIGPIPE handling (broken pipe errors)
- [ ] Handles large data streams without blocking
- [ ] Works with builtins and external commands
- [ ] cargo test passes (all tests including new pipeline tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: complex pipelines with 5+ stages

## Technical Notes
- Review and harden src/executor/pipeline.rs
- Add comprehensive pipeline tests
- Handle backpressure and buffering
- Test with large files and many pipeline stages" \
  --priority=1 \
  --labels="rush,1.0,backend,critical" \
  --silent)

echo "Story 3 created: $STORY_3"

# Story 2: File Redirections (depends on Story 3)
echo "Creating Story 2: File Redirections..."
STORY_2=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-002: File Redirections" \
  --description="As a shell user, I want standard Unix redirections (>, >>, 2>, &>) so that I can redirect output to files like any Unix shell.

## Acceptance Criteria
- [ ] stdout redirection: \`echo \"test\" > file.txt\`
- [ ] Append mode: \`echo \"more\" >> file.txt\`
- [ ] stderr redirection: \`command 2> errors.log\`
- [ ] Combined redirection: \`command &> output.log\`
- [ ] Input redirection: \`command < input.txt\`
- [ ] Works with pipes: \`cmd | grep foo > results.txt\`
- [ ] cargo test passes (all tests including new redirection tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: verify files created with correct content

## Technical Notes
- Extend src/executor/pipeline.rs
- Parse redirection operators in lexer/parser
- Handle file creation/appending
- Properly separate stdout/stderr streams" \
  --priority=2 \
  --labels="rush,1.0,backend,critical" \
  --silent)

echo "Story 2 created: $STORY_2"
echo "Adding dependency: Story 2 depends on Story 3..."
bd dep add "$STORY_2" "$STORY_3"

# Story 1: Script Execution (Foundation - no dependencies)
echo "Creating Story 1: Script Execution..."
STORY_1=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-001: Script Execution" \
  --description="As a developer, I want to execute Rush shell scripts from files so that I can automate tasks and run saved scripts.

## Acceptance Criteria
- [ ] Can execute .rush files: \`rush script.rush\`
- [ ] Shebang support: \`#!/usr/bin/env rush\`
- [ ] Script arguments accessible via \$1, \$2, etc.
- [ ] Exit codes propagate correctly
- [ ] Error messages show script name and line number
- [ ] Scripts can source other scripts
- [ ] cargo test passes (all tests including new script execution tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: run sample scripts with various features

## Technical Notes
- Modify src/executor/mod.rs to accept file input
- Add script argument parsing
- Implement file reading and execution loop
- Add line number tracking for errors" \
  --priority=1 \
  --labels="rush,1.0,backend,critical" \
  --silent)

echo "Story 1 created: $STORY_1"

# Story 4: Configuration File Support (depends on Story 1)
echo "Creating Story 4: Configuration File Support..."
STORY_4=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-004: Configuration File Support" \
  --description="As a Rush user, I want a startup config file (~/.rushrc) so that I can customize my environment, aliases, and preferences.

## Acceptance Criteria
- [ ] Loads ~/.rushrc on startup (if exists)
- [ ] Supports setting environment variables
- [ ] Supports defining aliases
- [ ] Supports defining functions
- [ ] Supports setting shell options
- [ ] Errors in config show helpful messages
- [ ] Can skip config with --no-config flag
- [ ] cargo test passes (all tests including config tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: create ~/.rushrc and verify it loads

## Technical Notes
- Create config module
- Parse Rush script syntax from file
- Execute config before REPL starts
- Add error handling for bad config
- Document config file format" \
  --priority=2 \
  --labels="rush,1.0,feature" \
  --silent)

echo "Story 4 created: $STORY_4"
echo "Adding dependency: Story 4 depends on Story 1..."
bd dep add "$STORY_4" "$STORY_1"

# Story 5: Confirmation Prompts (no dependencies)
echo "Creating Story 5: Confirmation Prompts for Destructive Operations..."
STORY_5=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-005: Confirmation Prompts for Destructive Operations" \
  --description="As a cautious user, I want confirmation prompts before destructive operations so that I don't accidentally delete important files.

## Acceptance Criteria
- [ ] rm -rf prompts for confirmation
- [ ] Shows what will be deleted (file count, size)
- [ ] y/N prompt with default to No
- [ ] Can force with --yes flag to skip prompt
- [ ] Works in scripts (auto-yes or auto-no based on flag)
- [ ] Integrates with undo system
- [ ] cargo test passes (all tests including prompt tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: verify prompts appear and work correctly

## Technical Notes
- Add prompt logic to rm builtin
- Calculate total size before deletion
- Add --yes and --force flags
- Make it work non-interactively for scripts" \
  --priority=2 \
  --labels="rush,1.0,safety,feature" \
  --silent)

echo "Story 5 created: $STORY_5"

# Story 6: Better Error Messages (no dependencies, shares code with Story 8)
echo "Creating Story 6: Better Error Messages with Suggestions..."
STORY_6=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-006: Better Error Messages with Suggestions" \
  --description="As a user who makes typos, I want helpful error messages with suggestions so that I can quickly fix my mistakes.

## Acceptance Criteria
- [ ] \"command not found\" suggests similar commands
- [ ] Uses fuzzy matching (edit distance)
- [ ] Suggests from builtins, aliases, and PATH
- [ ] Shows \"Did you mean: X?\" for close matches
- [ ] Suggests common flag typos
- [ ] Works for Git commands and other builtins
- [ ] cargo test passes (all tests including suggestion tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: verify suggestions for common typos

## Technical Notes
- Implement fuzzy string matching (use strsim or similar)
- Build suggestion system
- Integrate into error handling
- Add tests for common typos" \
  --priority=3 \
  --labels="rush,1.0,ux,feature" \
  --silent)

echo "Story 6 created: $STORY_6"

# Story 8: Command Suggestions (no dependencies, shares code with Story 6)
echo "Creating Story 8: Command Suggestions..."
STORY_8=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-008: Command Suggestions (Did You Mean?)" \
  --description="As a user learning Rush, I want command suggestions when I mistype so that I can discover the correct command.

## Acceptance Criteria
- [ ] Typo detection for commands: \"carg\" → \"cargo\"
- [ ] Suggests from command history
- [ ] Suggests based on current context (git repo → git commands)
- [ ] Configurable threshold for suggestions
- [ ] Shows multiple suggestions if close match
- [ ] Works for both builtins and external commands
- [ ] cargo test passes (all tests including suggestion tests)
- [ ] cargo build --release succeeds
- [ ] cargo clippy -- -D warnings passes
- [ ] Manual testing: verify context-aware suggestions

## Technical Notes
- Reuse fuzzy matcher from Story 6 or history module
- Build command suggestion index
- Integrate with error handling
- Add configuration option to disable" \
  --priority=3 \
  --labels="rush,1.0,ux,feature" \
  --silent)

echo "Story 8 created: $STORY_8"

# Story 7: CI/CD and Distribution (no dependencies)
echo "Creating Story 7: CI/CD and Distribution..."
STORY_7=$(bd create \
  --parent="$EPIC_ID" \
  --title="US-007: CI/CD and Distribution" \
  --description="As a potential Rush user, I want easy installation via package managers so that I don't have to build from source.

## Acceptance Criteria
- [ ] GitHub Actions workflow for releases
- [ ] Pre-built binaries for macOS (Intel + ARM)
- [ ] Pre-built binaries for Linux (x86_64)
- [ ] Homebrew formula
- [ ] Installation instructions in README
- [ ] Version tags trigger automated builds
- [ ] Checksums for all binaries
- [ ] GitHub Actions workflow runs successfully
- [ ] Test installation on clean macOS machine
- [ ] Test installation on clean Linux machine

## Technical Notes
- Create .github/workflows/release.yml
- Set up cross-compilation
- Create Homebrew tap
- Document installation process
- Test on clean machines" \
  --priority=4 \
  --labels="rush,1.0,infrastructure,distribution" \
  --silent)

echo "Story 7 created: $STORY_7"

echo ""
echo "✅ Epic and all beads created successfully!"
echo ""
echo "Epic: $EPIC_ID"
echo "  - $STORY_3 (US-003: Robust Pipeline Implementation)"
echo "  - $STORY_2 (US-002: File Redirections) [depends on $STORY_3]"
echo "  - $STORY_1 (US-001: Script Execution)"
echo "  - $STORY_4 (US-004: Configuration File Support) [depends on $STORY_1]"
echo "  - $STORY_5 (US-005: Confirmation Prompts)"
echo "  - $STORY_6 (US-006: Better Error Messages)"
echo "  - $STORY_8 (US-008: Command Suggestions)"
echo "  - $STORY_7 (US-007: CI/CD and Distribution)"
echo ""
echo "To start working on this epic, run:"
echo "  helix ~/helix --epic $EPIC_ID"
echo ""
echo "Or to let helix pick the next unblocked task:"
echo "  helix ~/helix"
